### PR TITLE
fix deprecations

### LINKED ISSUE #325: Deprecated methods and classes
The current 6.3.1 version uses the following deprecated methods/classes:

- `\Cake\Datasource\ModelAwareTrait::loadModel()` which will be removed in CakePHP 5.0 and is replaced by `\Cake\ORM\Locator\LocatorAwareTrait::fetchTable()`

image

Do you want to add a dev-dependency to https://github.com/CakeDC/cakephp-phpstan so phpstan knows how to interpret the return types of `fetchTable()`?

With that: Do you want to raise the min-php version to PHP 7.4 just as CakePHP 4.4 will do? With that we can add property types instead of relying on the phpdoc definitions.

- `\Cake\Filesystem\Folder` is used in the `OldTaskFinder` (which may get removed anyway?) and the current `TaskFinder`

This will need to be replaced with PHP native SPL classes. I can look into that if you want.

What do you say, @dereuromark? Or do you have something planed anyway?

### PR DESCRIPTION
**Pull request by LordSimal**
Fixes #325

BUT there is still a problem which I can't really get my head around.

Its about the new `->fetchTable()` method from the `LocatorAwareTrait` not returning the "correct" types even though https://github.com/CakeDC/cakephp-phpstan is installed.

I was able to easily replace the deprecated `Cake\Filesystem\Folder` class usages with just some plain old `glob()` functions. No need for SPL classes.

The changes in the `composer.json` are just my editor re-ordering the packages alphabatically. If this is a problem I can for sure just return that to its original state (and I declared to use phpstan 1.5 and requiring PHP 7.4)

### CODE REVIEW

**Comment by LordSimal** [comment]
Had to bump up to `"cakephp/cakephp": "^4.3.0"`, otherwise prefer-lowest wouldn't work because `fetchTable()` has been introduced in 4.3

File: src/Migration/OldTaskFinder.php [hunk 1]
```diff
@@ -36,16 +35,17 @@ public function all(?string $plugin) {
...
+		$res = glob($path . '*Task.php');
 
 		$tasks = [];
-		foreach ($res as $key => $r) {
-			$name = basename($r, 'Task.php');
-			$name = substr($name, 5);
-
-			$taskKey = $plugin ? $plugin . '.' . $name : $name;
-			$tasks[$taskKey] = $path . $r;
+		if($res) {
```
Comment (dereuromark) [inline src/Migration/OldTaskFinder.php:41]: cs issues

Comment (LordSimal) [reply src/Migration/OldTaskFinder.php:41]: Had to add that if there because `glob()` can return `false` on error.
But I will more restrictly check if that result is not false.

**Comment by LordSimal** [comment]
But I still have no idea how we should handle the missing "correct" return-types of `fetchTable()`

File: src/Migration/OldTaskFinder.php (hunk 1 above)
Comment (dereuromark) [reply src/Migration/OldTaskFinder.php]: talking about whitespace

File: src/Migration/OldTaskFinder.php [hunk 2]
```diff
@@ -38,7 +38,7 @@ protected function getTasks(string $path, ?string $plugin) {
 		$res = glob($path . '*Task.php');
 
 		$tasks = [];
-		if($res) {
+		if($res !== false) {
```
Comment (dereuromark) [inline src/Migration/OldTaskFinder.php:41]: I would actually much prefer the previous way..

Comment (LordSimal) [reply src/Migration/OldTaskFinder.php:41]: well then I am not sure what you mean by CS issues then ^^

File: src/Migration/OldTaskFinder.php (hunk 1 above)
Comment (LordSimal) [reply src/Migration/OldTaskFinder.php]: ahhhhh, but then why is there no cs-rule present for that?

Comment (dereuromark) [reply src/Migration/OldTaskFinder.php]: I am sure there is, you just didnt execute it.

Comment (LordSimal) [reply src/Migration/OldTaskFinder.php]: just saying, I executed `composer cs-fix` and there was nothing changed so there is nothing wrong (with no space between if and the `(`)

Comment (LordSimal) [reply src/Migration/OldTaskFinder.php]: but for some reason `composer cs-check` does report it

File: src/Migration/OldTaskFinder.php (hunk 2 above)
Comment (LordSimal) [reply src/Migration/OldTaskFinder.php]: Reverted it back to how it was

File: src/Command/InfoCommand.php [hunk 3]
```diff
@@ -79,7 +79,7 @@ public function execute(Arguments $args, ConsoleIo $io) {
 		$io->out();
 
 		$io->out('Total unfinished jobs: ' . $this->QueuedJobs->getLength());
-		$this->loadModel('Queue.QueueProcesses');
+		$this->QueueProcesses = $this->fetchTable('Queue.QueueProcesses');
```
Comment (dereuromark) [inline src/Command/InfoCommand.php:82]: something must still be wrong, as PHPStan doesnt like it yet.

File: src/Migration/OldTaskFinder.php [hunk 4]
```diff
@@ -36,16 +35,17 @@ public function all(?string $plugin) {
...
+		$res = glob($path . '*Task.php');
 
 		$tasks = [];
-		foreach ($res as $key => $r) {
-			$name = basename($r, 'Task.php');
-			$name = substr($name, 5);
-
-			$taskKey = $plugin ? $plugin . '.' . $name : $name;
-			$tasks[$taskKey] = $path . $r;
+		if ($res) {
```
Comment (dereuromark) [inline src/Migration/OldTaskFinder.php:41]: instead of nesting, why not just `glob() ?: []` ?

File: src/Queue/TaskFinder.php [hunk 5]
```diff
@@ -75,21 +74,21 @@ public function all(): array {
...
-			$namespace = $plugin ? str_replace('/', '\\', $plugin) : Configure::read('App.namespace');
-
-			/** @phpstan-var class-string<\Queue\Queue\Task> $className */
-			$className = $namespace . '\Queue\Task\\' . $name . 'Task';
-			$key = $plugin ? $plugin . '.' . $name : $name;
-
-			if (!in_array($className, $ignoredTasks, true)) {
-				$tasks[$key] = $className;
+		$files = glob($path . '*Task.php');
+		if ($files) {
```
Comment (dereuromark) [inline src/Queue/TaskFinder.php:80]: Same here

File: src/Queue/Task.php [hunk 6]
```diff
@@ -95,9 +95,10 @@ public function __construct(?Io $io = null, ?LoggerInterface $logger = null) {
 		$this->io = $io ?: new Io(new ConsoleIo());
 		$this->logger = $logger;
 
-		$this->loadModel($this->queueModelClass);
+		$tableLocator = $this->getTableLocator();
+		$this->QueuedJobs = $tableLocator->get($this->queueModelClass);
```
Comment (LordSimal) [inline src/Queue/Task.php:99]: Not really sure how we should tackle this. Should we remove that property, set it hardcoded as string and therefore remove the posibility to set a custom QueueModelClass?

File: src/Migration/OldTaskFinder.php (hunk 4 above)
Comment (dereuromark) [reply src/Migration/OldTaskFinder.php:41]: The if nesting seems weird

Comment (LordSimal) [reply src/Migration/OldTaskFinder.php:41]: I think I get it now

File: src/Queue/Task.php (hunk 6 above)
Comment (mainpal1) [reply src/Queue/Task.php:99]: Could you please try the following? Not really sure if it would work.
`
        /**
         * @var \Queue\Model\Table\QueuedJobsTable
         */
        $QueuedJobs = $tableLocator->get($this->queueModelClass);

        $this->QueuedJobs = $QueuedJobs;
`

Comment (LordSimal) [reply src/Queue/Task.php]: Looks pretty good! Thanks 👍🏻

**Comment by LordSimal** [comment]
@dereuromark please check again if everything seems OK now.
