### PR TITLE
fix CakePHP 4.3 deprecation warnings in routes.php

### LINKED ISSUE #303: Deprecation warnings with CakePHP 4.3
If you open up DebugKit with CakePHP 4.3 and version 6.1.0 of this plugin you get the following warnings:

```
CAKE/Core/functions.php:322
`Router::prefix()` is deprecated, use the non-static method `RouterBuilder::prefix()` instead. - /Users/kevin/Documents/Sunlime/alfred/vendor/dereuromark/cakephp-queue/config/routes.php, line: 12 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `vendor/dereuromark/cakephp-queue/config/routes.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file.
CAKE/Core/functions.php:322
`Router::scope()` is deprecated, use the non-static method `RouterBuilder::scope()` instead. - /Users/kevin/Documents/Sunlime/alfred/vendor/cakephp/cakephp/src/Routing/Router.php, line: 875 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `vendor/cakephp/cakephp/src/Routing/Router.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file.
CAKE/Core/functions.php:322
`Router::plugin()` is deprecated, use the non-static method `RouterBuilder::plugin()` instead. - /Users/kevin/Documents/Sunlime/alfred/vendor/dereuromark/cakephp-queue/config/routes.php, line: 16 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `vendor/dereuromark/cakephp-queue/config/routes.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file.
CAKE/Core/functions.php:322
`Router::scope()` is deprecated, use the non-static method `RouterBuilder::scope()` instead. - /Users/kevin/Documents/Sunlime/alfred/vendor/cakephp/cakephp/src/Routing/Router.php, line: 912 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, or add `vendor/cakephp/cakephp/src/Routing/Router.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` to mute deprecations from only this file.
```

### PR DESCRIPTION
**Pull request by LordSimal**
Fixes #303

I am not able to run all tests locally because I am not on Linux (and your tests require linux)

But this actually fixes the deprecation warning in CakePHP 4.3 but should still be backwards compatible.

### CODE REVIEW

**Comment by LordSimal** [comment]
Those CS errors are not part of my change but if you want I can make a separate PR to fix those

File: config/routes.php [hunk 1]
```diff
@@ -1,16 +1,18 @@
...
 	$routes->plugin('Queue', function (RouteBuilder $routes) {
 		$routes->connect('/', ['controller' => 'Queue', 'action' => 'index']);
 
 		$routes->fallbacks();
 	});
 });
 
-Router::plugin('Queue', ['path' => '/queue'], function (RouteBuilder $routes) {
+$routes->plugin('Queue', ['path' => '/queue'], function (RouteBuilder $routes) {
 	$routes->connect('/:controller');
```
Comment (ADmad) [inline config/routes.php:17]:
```suggestion
	$routes->connect('/{controller}');
```

**Comment by dereuromark** [comment]
Thank you!
